spring:
  application:
    name: web_back_application

  data:
    redis:
      host: localhost
      port: 6379
      password:
      username: default
      database: 0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_blogger?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  web:
    resources:
      add-mappings: true
  mail:
    host: smtp.163.com
    username: Yomiger@163.com
    password: ZQDPOXMXRHDYPWWZ
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 5MB
server:
  port: 8080
  servlet:
    context-path: /nko-api

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml


---
nko:
  jwtKey: NKOYauusee
  directoryName: anyMd
  filePath: D:/MyCodes/MyBloggerWebSite/web_back/user/
